### Encoding Techniques
- LabelEncoder
- OneHotEncoder
- OrdinalEncoder
- TargetEncoder

In [32]:
import pandas as pd
import numpy as np
# Set random seed for reproducibility
np.random.seed(42)
# Generate 1000 rows with 4 columns
n_rows = 1000
data = {
    'color': np.random.choice(['red', 'blue', 'green'], n_rows),
    'size': np.random.choice(['small', 'medium', 'large'], n_rows),
    'material': np.random.choice(['plastic', 'metal', 'wood'], n_rows),
    'price': np.random.randint(10, 500, n_rows)
}
df = pd.DataFrame(data)

# Display first few rows
print(df.head())
print(f"\nDataset shape: {df.shape}")

   color   size material  price
0  green  large    metal    423
1    red  large  plastic    351
2  green  large  plastic    229
3  green  large     wood    400
4    red  small  plastic    172

Dataset shape: (1000, 4)

In [33]:
df.head()

   color   size material  price
0  green  large    metal    423
1    red  large  plastic    351
2  green  large  plastic    229
3  green  large     wood    400
4    red  small  plastic    172

In [34]:
# pip install category_encoders

In [35]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [36]:
X = df.drop(columns='price')
y= df.price
xtrain,xtest,ytrain,yest = train_test_split(X,y,train_size=0.8,random_state=42)

### Label encoder()

In [37]:
label_encoder = LabelEncoder()
''' 
# updated_xtrain = label_encoder.fit_transform(xtrain)
ValueError: y should be a 1d array, 
got an array of shape (800, 3) instead.

'''

' \n# updated_xtrain = label_encoder.fit_transform(xtrain)\nValueError: y should be a 1d array, \ngot an array of shape (800, 3) instead.\n\n'

In [38]:
label_encoder.fit_transform(xtrain['color'])

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2, 1,
       1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 2, 0,
       2, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 1,
       0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1,
       1, 1, 0, 1, 0, 0, 2, 2, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2, 2, 1, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 2, 2,
       0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 1, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2,
       1, 1, 0, 0, 1, 0, 2, 0, 2, 1, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 0,
       1, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2,
       0, 2, 0, 0, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 1, 1,
       0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1,
       2, 1, 0, 2, 2, 0, 0, 1])

In [39]:
#label_encoder.transform(xtest)
#ValueError: y should be a 1d array, got an array of shape (200, 3) instead.

In [40]:
#new_input(unseen data)
new_input=['red','red']
label_encoder.transform(new_input)

array([2, 2])

## OneHotEncoder()

In [41]:
#onehot encoder

#1st method
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
values=encoder.fit_transform(xtrain)
#toarray()
values=values.toarray()
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [42]:
#onehot encoder

#2nd method
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)
values=encoder.fit_transform(xtrain)
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [43]:
#returns column names
columns=encoder.get_feature_names_out()

In [44]:
pd.DataFrame(values,columns=columns).astype(int)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0,1,0,0,0,1,0,0,1
1,1,0,0,0,1,0,1,0,0
2,1,0,0,0,0,1,0,0,1
3,0,0,1,0,0,1,0,1,0
4,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
795,0,0,1,1,0,0,0,1,0
796,0,0,1,0,0,1,0,1,0
797,1,0,0,1,0,0,0,1,0
798,1,0,0,0,0,1,0,1,0
799,0,1,0,0,0,1,0,1,0

In [45]:
#same no of columns should be transferred in fit_transform and transform method, otherwise we get valueError


'''encoder.transform(xtest[['color','size']])
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- material
'''

encoder.transform(xtest)#valid syntax becoz xtest is 2-D

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(200, 9))

In [46]:
'''new_input=[['red'],['large']]
encoder.transform(new_input)

ValueError: X has 1 features, but OneHotEncoder is expecting 3 features as input.
'''

'''new_input=[['red','large'],['blue','small']]
encoder.transform(new_input)

ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
'''



'''
new_input=[['white','large','plastic'],['blue','small','wood']]
encoder.transform(new_input)

ValueError: Found unknown categories ['white'] in column 0 during transform
'''
#valid
new_input=[['red','large','plastic'],['blue','small','wood']]
encoder.transform(new_input)

C:\Users\lahar\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [47]:
'''
encoder=OneHotEncoder(sparse_output=False,handle_unknown='error')
values=encoder.fit_transform(xtrain)
new_input=[['red1','large','plastic'],['blue','small','wood']]
encoder.transform(new_input)

ValueError: Found unknown categories ['red1'] in column 0 during transform
'''


encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
updated_xtrain=encoder.fit_transform(xtrain)

new_input=[['red1','large1','plastic'],['blue','small','wood']]
# new_input=pd.DataFrame(data=[['red1','large1','plastic'],['blue','small','wood']],columns=['color','size','material'])--->dosen't gives warning message
encoder.transform(new_input)

C:\Users\lahar\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [48]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

### fit_transform()

objname.fit_transform(xtrain)---->valid

objname.fit_transform(xtest)

objname.fit_transform([[values]])

objname.fit_transform(x)

### transform()

objname.tansform(xtrain)--->invalid

valid..

objname.fit_transform(xtrain)

objname.transform(xtest)

objname.transform([new_input])

## OrdinalEncoder

In [49]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
updated_xtrain=encoder.fit_transform(xtrain)
updated_xtrain

# '''
# updated_xtrain=encoder.fit_transform(xtrain['color'])

# ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead.
# Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
# '''

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]], shape=(800, 3))

In [50]:
encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [51]:
updated_xtest=encoder.transform(xtest)
updated_xtest

# '''
# updated_xtest=encoder.transform(xtest['color'])
# ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead.
# Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
# '''

array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [0., 2., 0.],
       [2., 2., 2.],
       [0., 2., 2.],
       [0., 2., 0.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [0., 0., 0.],
       [1., 2., 1.],
       [2., 1., 2.],
       [2., 2., 2.],
       [1., 2., 1.],
       [2., 1., 0.],
       [2., 2., 1.],
       [1., 1., 1.],
       [2., 0., 0.],
       [1., 0., 1.],
       [1., 2., 2.],
       [1., 2., 2.],
       [0., 2., 0.],
       [1., 1., 1.],
       [1., 1., 2.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 2., 1.],
       [1., 1., 2.],
       [0., 1., 1.],
       [0., 2., 2.],
       [2., 0., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [0., 2., 2.],
       [2., 2., 0.],
       [0., 0., 2.],
       [2., 0., 2.],
       [2., 0., 1.],
       [0., 0., 0.],
       [2., 0., 2.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 0., 2.],
       [0., 2., 1.],
       [0., 0., 0.],
       [1., 1., 2.],
       [0., 1., 2.],
       [2., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.],
       [1., 1., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 2., 1.],
       [0., 0., 2.],
       [0., 0., 2.],
       [2., 0., 2.],
       [1., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [2., 2., 0.],
       [0., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 2., 2.],
       [2., 2., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [0., 2., 2.],
       [2., 1., 1.],
       [1., 2., 1.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 1., 2.],
       [0., 0., 0.],
       [2., 1., 0.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 0., 2.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 0., 2.],
       [1., 0., 2.],
       [2., 2., 1.],
       [2., 2., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [0., 1., 2.],
       [2., 1., 2.],
       [2., 1., 2.],
       [2., 0., 2.],
       [0., 0., 0.],
       [0., 2., 0.],
       [2., 1., 1.],
       [2., 1., 2.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [2., 2., 0.],
       [1., 1., 0.],
       [2., 1., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [1., 2., 1.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 1., 0.],
       [2., 2., 2.],
       [2., 1., 0.],
       [0., 1., 0.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 2., 0.],
       [2., 2., 2.],
       [1., 2., 0.],
       [0., 0., 0.],
       [1., 2., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 2., 0.],
       [0., 1., 0.],
       [2., 1., 0.],
       [0., 1., 2.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 2., 0.],
       [1., 2., 1.],
       [1., 1., 1.]])

In [52]:
# encoder=OrdinalEncoder(handle_unknown='error')
encoder=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)

updated_xtrain=encoder.fit_transform(xtrain)
updated_xtest=encoder.transform(xtest)
# new_data=[['white','small','wood'],['red','small','wood']]
new_data=pd.DataFrame(data=[['white','small','wood'],['red','small','wood']],columns=['color','size','material'])#removes warning message
updated_new_data=encoder.transform(new_data)
updated_new_data

array([[-1.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [53]:
#encoder=OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=1)
'''
encoder.fit_transform(xtrain)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).
why??
becoz--->xtrain is having 3 columns and categories=[[col_order]]
shape mismatching

when xtrain columns==col_orders then it will tansform the values(fit_transform)
'''

'\nencoder.fit_transform(xtrain)\n\nValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).\nwhy??\nbecoz--->xtrain is having 3 columns and categories=[[col_order]]\nshape mismatching\n\nwhen xtrain columns==col_orders then it will tansform the values(fit_transform)\n'

encoder=OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1)

In [54]:
encoder=OrdinalEncoder(categories=[['green1','blue','red'],['small','medium','large'],['plastic', 'metal', 'wood']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)

'''
encoder.fit_transform(xtrain[['color','size']])
ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).
-->becoz in order we have mentions 3 cols values and we have passed only 2 cols
-->we have mention same no of columns whils assigning order and fit_tranform
'''

"\nencoder.fit_transform(xtrain[['color','size']])\nValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).\n-->becoz in order we have mentions 3 cols values and we have passed only 2 cols\n-->we have mention same no of columns whils assigning order and fit_tranform\n"

In [55]:
encoder=OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],['plastic', 'metal', 'wood']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)

array([[0., 0., 2.],
       [1., 1., 1.],
       [1., 0., 2.],
       ...,
       [1., 2., 0.],
       [1., 0., 0.],
       [0., 0., 0.]], shape=(800, 3))

In [56]:
'''encoder=OrdinalEncoder(categories=[['small','medium','large'],['green1','blue','red'],['plastic', 'metal', 'wood']],handle_unknown='use_encoded_value')
encoder.fit_transform(xtrain)

TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.

becoz we didn't mention which encoded value should be used

'''

"encoder=OrdinalEncoder(categories=[['small','medium','large'],['green1','blue','red'],['plastic', 'metal', 'wood']],handle_unknown='use_encoded_value')\nencoder.fit_transform(xtrain)\n\nTypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.\n\nbecoz we didn't mention which encoded value should be used\n\n"

In [57]:
encoder.transform(xtest)

array([[2., 0., 1.],
       [2., 0., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 0.],
       [0., 2., 0.],
       [2., 0., 0.],
       [2., 2., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 2., 1.],
       [2., 2., 0.],
       [1., 1., 2.],
       [0., 0., 1.],
       [2., 2., 1.],
       [0., 1., 2.],
       [2., 2., 0.],
       [2., 2., 2.],
       [1., 2., 1.],
       [0., 2., 1.],
       [0., 1., 1.],
       [0., 0., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [1., 1., 2.],
       [0., 2., 1.],
       [2., 0., 1.],
       [1., 0., 1.],
       [0., 1., 0.],
       [2., 1., 1.],
       [2., 2., 2.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [1., 2., 2.],
       [2., 0., 2.],
       [2., 1., 0.],
       [2., 1., 1.],
       [0., 2., 1.],
       [2., 0., 2.],
       [2., 1., 2.],
       [0., 2., 1.],
       [2., 2., 0.],
       [1., 2., 0.],
       [0., 2., 2.],
       [0., 2., 2.],
       [0., 0., 2.],
       [0., 1., 1.],
       [0., 2., 0.],
       [0., 2., 2.],
       [1., 2., 2.],
       [1., 0., 1.],
       [2., 0., 2.],
       [1., 0., 2.],
       [1., 0., 1.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 2., 1.],
       [2., 2., 0.],
       [1., 1., 2.],
       [1., 2., 1.],
       [0., 0., 0.],
       [2., 1., 2.],
       [2., 0., 2.],
       [0., 0., 0.],
       [2., 1., 1.],
       [2., 0., 0.],
       [0., 1., 0.],
       [2., 2., 1.],
       [0., 2., 0.],
       [0., 0., 2.],
       [0., 0., 2.],
       [1., 0., 1.],
       [0., 1., 0.],
       [0., 1., 2.],
       [1., 2., 0.],
       [0., 2., 0.],
       [1., 0., 0.],
       [0., 1., 2.],
       [1., 1., 0.],
       [1., 0., 2.],
       [2., 2., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [2., 1., 1.],
       [0., 2., 1.],
       [1., 0., 2.],
       [2., 0., 1.],
       [1., 2., 2.],
       [2., 2., 2.],
       [2., 2., 0.],
       [1., 2., 1.],
       [2., 2., 2.],
       [1., 1., 1.],
       [0., 1., 1.],
       [2., 2., 2.],
       [1., 0., 0.],
       [1., 2., 1.],
       [0., 1., 2.],
       [1., 1., 2.],
       [2., 2., 1.],
       [1., 1., 0.],
       [1., 2., 1.],
       [2., 0., 2.],
       [0., 1., 0.],
       [2., 2., 0.],
       [2., 2., 1.],
       [2., 2., 2.],
       [2., 0., 0.],
       [1., 2., 2.],
       [1., 2., 2.],
       [2., 2., 2.],
       [0., 0., 0.],
       [0., 0., 1.],
       [2., 2., 1.],
       [2., 1., 2.],
       [1., 2., 0.],
       [2., 0., 2.],
       [2., 1., 0.],
       [2., 1., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [2., 0., 1.],
       [1., 2., 1.],
       [2., 2., 1.],
       [2., 2., 1.],
       [2., 2., 2.],
       [0., 2., 2.],
       [1., 0., 2.],
       [2., 0., 1.],
       [2., 1., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [2., 1., 0.],
       [0., 0., 0.],
       [2., 1., 2.],
       [1., 2., 0.],
       [2., 1., 2.],
       [1., 2., 1.],
       [2., 1., 1.],
       [0., 1., 0.],
       [0., 0., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [2., 2., 1.],
       [2., 2., 2.],
       [2., 2., 1.],
       [1., 2., 2.],
       [0., 2., 2.],
       [2., 0., 0.],
       [2., 0., 2.],
       [1., 2., 0.],
       [0., 0., 2.],
       [1., 1., 2.],
       [2., 1., 2.],
       [2., 1., 2.],
       [2., 2., 2.],
       [1., 2., 1.],
       [1., 0., 1.],
       [2., 1., 0.],
       [2., 1., 2.],
       [0., 2., 0.],
       [0., 1., 1.],
       [0., 1., 0.],
       [2., 2., 0.],
       [1., 1., 0.],
       [2., 0., 1.],
       [0., 1., 1.],
       [2., 1., 2.],
       [0., 1., 2.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 0.],
       [1., 2., 2.],
       [1., 1., 1.],
       [2., 0., 2.],
       [2., 1., 1.],
       [1., 1., 1.],
       [2., 1., 0.],
       [1., 2., 0.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 1.],
       [1., 2., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [1., 2., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [1., 1., 2.],
       [1., 2., 2.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 0., 1.],
       [2., 2., 1.],
       [2., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.]])

In [58]:
#obj_cols=[]-->not valid
obj_cols=xtrain.select_dtypes(include='object').columns
num_cols=xtrain.select_dtypes(include='number').columns
obj_cols
# num_cols

C:\Users\lahar\AppData\Local\Temp\ipykernel_17372\457786500.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols=xtrain.select_dtypes(include='object').columns

Index(['color', 'size', 'material'], dtype='str')

In [59]:
# we can use this target encoder when we have mixed(categorical and numerical) columns
from category_encoders import TargetEncoder
encoder=TargetEncoder(cols=['color'],handle_unknown='value')#we have to mention only categorical column for cols
#if there is any unknown values-->handle_unknown='value'-->assigns unknown values by taking avg of all the values
encoder.fit_transform(xtrain,ytrain)
encoder.transform(xtest)

          color    size material
521  263.678700   small    metal
737  263.678700   small    metal
740  256.408397   small    metal
660  253.164751   small  plastic
411  256.408397  medium    metal
..          ...     ...      ...
408  253.164751   small    metal
332  263.678700   large    metal
208  263.678700   small    metal
613  253.164751   small  plastic
78   253.164751  medium  plastic

[200 rows x 3 columns]

In [60]:
#new_input

""" new_input=[['red','small','wood1']]
encoder.transform(new_input)

KeyError: 'color'
"""
new_input=pd.DataFrame({
    'color':['red'],'size':['small'],'material':['wood']
    })
encoder.transform(new_input)

      color   size material
0  263.6787  small     wood

### Conclusion
- Explored various types of encoding techniques.
- Learned how to handle categorical columns and transform them into a format suitable for model training using the fit() method.
- Understood how to apply different encoding techniques effectively.
- Studied different scenarios to determine when each encoding technique is most appropriate.
- Learned how to identify, troubleshoot, and handle common encoding-related errors.